/*
 * (C) 2014 hayde.eu
 */
package eu.hayde.box.persistence.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(value = {ElementType.METHOD, ElementType.FIELD})
@Retention(value = RetentionPolicy.RUNTIME)
/**
 * column definition for a single field
 *
 * Position: field (variable <-> column)
 *
 * @author can.senturk
 */
public @interface Column {

    public String name() default "";				// (Optional) The name of the column.

    public boolean unique() default false;			// (Optional) Whether the property is a unique key.

    public boolean nullable() default true;			// (Optional) Whether the database column is nullable.

    public boolean insertable() default true;			// (Optional) Whether the column is included in SQL INSERT statements generated by the persistence provider.

    public boolean updatable() default true;			// (Optional) Whether the column is included in SQL UPDATE statements generated by the persistence provider.

    public String columnDefinition() default "";		// (Optional) The SQL fragment that is used when generating the DDL for the column.

    public String table() default "";				// (Optional) The name of the table that contains the column.

    public int length() default 255;				// (Optional) The column length.

    public int precision() default 0;				// (Optional) The precision for a decimal (exact numeric) column.

    public int scale() default 0;				// (Optional) The scale for a decimal (exact numeric) column.
}
